services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host 0.0.0.0 --port 5000"
    envVars:
      - key: CHROMIUM_PATH
        value: "/usr/bin/chromium"  # กำหนดตำแหน่งที่ติดตั้ง Chromium
      - key: DISPLAY
        value: ":99"  # ต้องกำหนด DISPLAY เมื่อใช้ headless mode
