services:
  - type: web
    name: gold-price-playwright
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python app.py
